#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <variant>
#include <vector>

// Private, inert snapshot framing. No dispatcher calls this yet. These types
// establish neither source authority nor durable acceptance/installation.
namespace lattice::detail::sync_recovery {

struct protocol_error : std::runtime_error {
    using std::runtime_error::runtime_error;
};

// Every caller supplies finite resource policy. Hard parser ceilings below do
// not constitute a product snapshot-size or disk-space promise.
struct limits {
    size_t frame_bytes;
    size_t depth;
    size_t nodes;
    size_t string_bytes;
    size_t rows_per_page;
    uint64_t pages;
    uint64_t total_rows;
    uint64_t total_bytes;
};

struct binding {
    std::string source_id;       // canonical lower-case UUID: physical source incarnation
    std::string epoch;           // canonical lower-case UUID: history incarnation
    std::string channel;         // exact configured logical channel, not a filesystem path
    std::string scope_digest;    // lowercase SHA-256 spelling; not verified here
    std::string schema_digest;
    std::string attempt_id;      // binds the requesting connection attempt
    std::string recovery_id;
    bool operator==(const binding&) const = default;
};

struct manifest {
    binding identity;
    // Required nullable field: null is an explicit beginning, never an absent
    // field, legacy fallback, maximum UUID or implicit checkpoint.
    std::optional<uint64_t> base_position;
    uint64_t frontier = 0;       // source-authoritative position, not upstream AuditLog.id
    uint64_t page_count = 0;
    uint64_t row_count = 0;
    uint64_t content_bytes = 0;
    std::string content_digest;
    bool operator==(const manifest&) const = default;
};

struct row {
    std::string table;
    std::string global_id;
    // Owned opaque UTF-8 payload. Model/schema/type parsing and payload hashing
    // are separate, mandatory installer work. No SQL is generated by this codec.
    std::string payload;
    bool operator==(const row&) const = default;
};

struct page {
    binding identity;
    uint64_t index = 0;
    uint64_t content_bytes = 0;
    std::string content_digest;
    std::vector<row> rows;
    bool operator==(const page&) const = default;
};

struct end {
    binding identity;
    uint64_t frontier = 0;
    uint64_t page_count = 0;
    uint64_t row_count = 0;
    uint64_t content_bytes = 0;
    std::string content_digest;
    bool operator==(const end&) const = default;
};

using message = std::variant<manifest, page, end>;

// Canonical content is each row's three UTF-8 strings, each preceded by its
// unsigned 64-bit big-endian byte length, in (table,global_id) byte order.
// This function counts that representation; it does NOT calculate its digest.
uint64_t canonical_row_bytes(const row& value);
uint64_t parse_position(std::string_view value); // 0..INT64_MAX, canonical decimal only

message decode(std::string_view frame, const limits& budget);
std::string encode(const message& value, const limits& budget);

enum class phase { receiving, sequence_complete_unverified };
struct staging_state {
    manifest offer;
    phase status = phase::receiving;
    uint64_t next_page = 0;
    uint64_t rows = 0;
    uint64_t content_bytes = 0;
    std::optional<std::pair<std::string, std::string>> last_identity;
    bool operator==(const staging_state&) const = default;
};

staging_state begin(const manifest& offer, const binding& expected, const limits& budget);
// Pure proposals: input state never changes, including on success. The journal
// owner must commit page bytes and returned state together before publishing it.
// Duplicate pages are refused without progress; restart requests start at the
// durable next_page. Exact row identities must increase across pages.
staging_state propose(const staging_state& current, const page& value, const limits& budget);
staging_state propose(const staging_state& current, const end& value, const limits& budget);

// Structural restart records only. Loading them is NOT proof that payloads are
// present, hashes verified, SQLite committed, or a model snapshot installed.
std::string encode_staging(const staging_state& value, const limits& budget);
staging_state decode_staging(std::string_view bytes, const binding& expected, const limits& budget);

} // namespace lattice::detail::sync_recovery
